sudo: false
language: python
python:
        - 2.7
        - 3.3
        - 3.4
install:
        - pip install coveralls
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
script : py.test nengo_spinnaker
after_success : coveralls
notifications:
        email: false
